
import javax.swing.JOptionPane;


public class CadPes extends javax.swing.JFrame {

    private Pessoa p1 = new Pessoa();
    private GerPes gp = new GerPes();
    
    
    public CadPes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtCpf = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        btInsPes = new javax.swing.JButton();
        btConsPesCpf = new javax.swing.JButton();
        btAltPesCpf = new javax.swing.JButton();
        btDelPesCpf = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Pessoas");

        rtCpf.setText("CPF:");

        rtNome.setText("NOME:");

        btInsPes.setText("Inserir");
        btInsPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsPesActionPerformed(evt);
            }
        });

        btConsPesCpf.setText("Consultar CPF");
        btConsPesCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsPesCpfActionPerformed(evt);
            }
        });

        btAltPesCpf.setText("Alterar CPF");

        btDelPesCpf.setText("Deletar CPF");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtNome)
                            .addComponent(rtCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btInsPes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsPesCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAltPesCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDelPesCpf)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsPes)
                    .addComponent(btConsPesCpf)
                    .addComponent(btAltPesCpf)
                    .addComponent(btDelPesCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btInsPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsPesActionPerformed
        insPes();
    }//GEN-LAST:event_btInsPesActionPerformed

    private void btConsPesCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsPesCpfActionPerformed
        consPesCpf();
    }//GEN-LAST:event_btConsPesCpfActionPerformed

    public void consPesCpf(){
        p1 = new Pessoa();
        p1.setCpf(Integer.parseInt(cxCpf.getText()));
        
        p1 = gp.consPesCpf(p1);
        
        if(p1 != null){
            
            cxCpf.setText(Integer.toString(p1.getCpf()));
            cxNome.setText(p1.getNome());
            JOptionPane.showMessageDialog(
                    null,
                    "Pessoa encontrada com sucesso! Verifique",
                    "Consulta de Pessoa",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                    null,
                    "Não existe pessoa com este CPF cadastrado",
                    "Consulta de Pessoa",
                    JOptionPane.ERROR_MESSAGE
            );
            cxCpf.setText("");
            cxCpf.requestFocus();
        }
    }
    
    public void insPes(){
        p1 = new Pessoa();
        try{
            p1.setCpf(Integer.parseInt(cxCpf.getText()));
            p1.setNome(cxNome.getText());

            p1 = gp.insPes(p1);

            if(p1 != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Pessoa cadastrada com sucesso!",
                        "Cadastro de Pessoa",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Já existe uma pessoa com este CPF",
                        "Cadastro de Pessoa",
                        JOptionPane.ERROR_MESSAGE
                );
                cxCpf.setText("");
                cxCpf.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                null,
                "O CPF deve ser um inteiro",
                "Erro de Dados",
                JOptionPane.ERROR_MESSAGE
            );
            cxCpf.setText("");
            cxCpf.requestFocus(); 
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            null,
            "Deseja realmente sair?",
            "Saida",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    public void limpar(){
        cxCpf.setText("");
        cxNome.setText("");
        cxCpf.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltPesCpf;
    private javax.swing.JButton btConsPesCpf;
    private javax.swing.JButton btDelPesCpf;
    private javax.swing.JButton btInsPes;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxNome;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtNome;
    // End of variables declaration//GEN-END:variables
}
